apiVersion: v1
kind: Namespace
metadata:
  name: app
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: myapp-config
  namespace: app
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: aws-ssm
    kind: ClusterSecretStore
  target:
    name: myapp-config
    creationPolicy: Owner
  data:
    - secretKey: APP_MESSAGE
      remoteRef:
        key: /myapp/APP_MESSAGE
